version: '4'
services:
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

  www1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./src:/var/www/html"
    depends_on:
      - db 
    expose:
      - "80"

  www2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./src:/var/www/html"
    depends_on:
      - db 
    expose:
      - "80"

  www3:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./src:/var/www/html"
    depends_on:
      - db 
    expose:
      - "80"
  
  recommendation:
    build:
      context: .
      dockerfile: PythonDockerfile
    volumes:
      - "./src/models:/app/models"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - www1
      - www2
      - www3
    ports:
      - "4000:4000"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306